# Generated by Django 2.0.4 on 2019-01-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина получения')),
                ('pass_number', models.CharField(max_length=100, verbose_name='Номер пропуска')),
                ('pass_level', models.PositiveSmallIntegerField(choices=[(0, 'Нет доступа'), (1, 'Гость'), (2, 'Сотрудник'), (8, 'Охранник'), (9, 'Руководитель'), (10, 'Владелец')], verbose_name='Уровень допуска')),
                ('is_single', models.BooleanField(default=True, verbose_name='Разовый')),
                ('date_open', models.DateTimeField(verbose_name='Дата открытия допуска')),
                ('date_close', models.DateTimeField(verbose_name='Дата закрытия допуска')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Закрыт')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Дата модификации')),
            ],
            options={
                'verbose_name': 'Уровень доступа',
                'verbose_name_plural': 'Уровни доступа',
            },
        ),
        migrations.CreateModel(
            name='Emploee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True, verbose_name='Момент события')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Разрешено'), (1, 'Запрещено')], verbose_name='Тип события')),
                ('access_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guards.AccessControl')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='Имя')),
                ('patronimyc', models.CharField(max_length=25, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('birth_date', models.DateField(verbose_name='Дата рожления')),
                ('document', models.CharField(max_length=25, verbose_name='Документ')),
                ('document_number', models.CharField(max_length=25, verbose_name='Номер')),
                ('document_date', models.DateField(verbose_name='Дата выдачи')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Дата модификации')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('min_access_level', models.PositiveSmallIntegerField(choices=[(0, 'Нет доступа'), (1, 'Гость'), (2, 'Сотрудник'), (8, 'Охранник'), (9, 'Руководитель'), (10, 'Владелец')], verbose_name='Минимальный уровень доступа')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guards.Place'),
        ),
        migrations.AddField(
            model_name='emploee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='guards.Person'),
        ),
        migrations.AddField(
            model_name='accesscontrol',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='guards.Person'),
        ),
    ]
