# Generated by Django 2.0.4 on 2018-12-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
            },
        ),
        migrations.CreateModel(
            name='DirectoryContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование контрагента')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryNomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'номенклатуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.OneToOneField(on_delete='SET NULL', related_name='producer', to='sales.DirectoryContractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='DirectoryProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.OneToOneField(on_delete='SET NULL', related_name='provider', to='sales.DirectoryContractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('nomenclatures', models.ManyToManyField(related_name='du_nomenclatures', to='sales.DirectoryNomenclature', verbose_name='Номенклатуры товаров')),
            ],
            options={
                'verbose_name': 'продажа (транзакция)',
                'verbose_name_plural': 'продажи',
            },
        ),
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Имя юзера')),
            ],
            options={
                'verbose_name': 'юзер приложения',
                'verbose_name_plural': 'юзеры приложения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete='SET NULL', related_name='seller', to='sales.DirectoryContractor', verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by',
            field=models.ForeignKey(on_delete='SET NULL', to='sales.SalesUser', verbose_name='Юзер'),
        ),
        migrations.AddField(
            model_name='directorynomenclature',
            name='producers',
            field=models.ManyToManyField(related_name='nomenclatures', to='sales.DirectoryProducer', verbose_name='Производители'),
        ),
        migrations.AddField(
            model_name='directorynomenclature',
            name='providers',
            field=models.ManyToManyField(related_name='nomenclatures', to='sales.DirectoryProvider', verbose_name='Поставщики'),
        ),
        migrations.AddField(
            model_name='check',
            name='sale',
            field=models.OneToOneField(on_delete='SET NULL', related_name='seller', to='sales.Sale', verbose_name='Юзер'),
        ),
    ]
