# Generated by Django 2.0.4 on 2018-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование контрагента')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryNomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'номенклатуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.OneToOneField(on_delete='SET NULL', related_name='producer', to='sales.DirectoryContractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='DirectoryProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.OneToOneField(on_delete='SET NULL', related_name='provider', to='sales.DirectoryContractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество закупки')),
                ('nomenclature', models.ForeignKey(on_delete='SET NULL', related_name='sales', to='sales.DirectoryNomenclature', verbose_name='Номенклатура товаров')),
            ],
            options={
                'verbose_name': 'продажа (транзакция)',
                'verbose_name_plural': 'продажи',
            },
        ),
        migrations.CreateModel(
            name='SaleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selled', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда продано')),
                ('summ', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, verbose_name='Сумма закупки')),
                ('sales', models.ManyToManyField(related_name='sale_check', to='sales.Sale', verbose_name='Закупка')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
            },
        ),
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Имя покупателя')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salecheck',
            name='sell_to',
            field=models.ForeignKey(on_delete='SET NULL', to='sales.SalesUser', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='directorynomenclature',
            name='producers',
            field=models.ManyToManyField(related_name='nomenclatures', to='sales.DirectoryProducer', verbose_name='Производители'),
        ),
        migrations.AddField(
            model_name='directorynomenclature',
            name='providers',
            field=models.ManyToManyField(related_name='nomenclatures', to='sales.DirectoryProvider', verbose_name='Поставщики'),
        ),
    ]
